name: 'Mandatory'
version: '1.0.0'
main: 'xyz.supeer.mandatory.Main'
api-version: '1.17'
depends: [NBTAPI]
author: 'superkrokodilen'
website: 'https://supeer.xyz'

commands:

  fly:

  broadcast:

  feed:

  me:

  vision:

  bosscast:

  gamemode:
    aliases: [g]

  speed:

  repair:

  balance:
    aliases: [b]

  player:
    aliases: [p]

  love:

  kick:

  modchat:
    aliases: [mc]

  admin:
    aliases: [ad]

  helpop:

  message:
    aliases: [msg,m]

  reply:
    aliases: [r]

  afk:

  buy:

  go:

  spawn:
    aliases: [s]

  teleportdeny:
    aliases: [tpno,tpdeny]

  teleportaccept:
    aliases: [tpyes,tpaccept]

  teleportask:
    aliases: [tpa,tpask]

  back:


